In [1]:
#Setting up the datasets. This part does not need to be taught in the lesson
!gdown "1mHc6bxlYBLY799zh9Sz4gmz7zBHhn7bF"
!gdown "1OwdaP3g9pk-gNx6008I3D5SljQRHN9my"

Downloading...
From: https://drive.google.com/uc?id=1mHc6bxlYBLY799zh9Sz4gmz7zBHhn7bF
To: /content/cars_features.csv
100% 4.35k/4.35k [00:00<00:00, 11.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1OwdaP3g9pk-gNx6008I3D5SljQRHN9my
To: /content/cars_features_clean.csv
100% 2.13k/2.13k [00:00<00:00, 7.85MB/s]

**Learning objectives**

*   The apprentice can demonstrate an understanding of how to load pandas and a dataset.
*   The apprentice can apply their knowledge to given examples.
*   The apprentice can demonstrate an understanding of how to clean a dataset and deal with null values.

**[note - you do not have to achieve all learning objectives. It is your prerogative to choose which learning objectives you aim to achieve in your session]**


***Workshop Task***

---



In this lesson will be explore the cars dataset and perform some data cleaning steps.

In [2]:
#import pandas

import pandas as pd

In [3]:
#load the data

cars=pd.read_csv('cars_features.csv')
type(cars)

pandas.core.frame.DataFrame

In [4]:
cars.head() #look at first 5 rows of the dataframe

,index,car,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,model.1,color
0,0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.62 lbs,16.46,NaN,1.0,4.0,4.0,RX4,NaN
1,1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875 lbs,17.02,NaN,1.0,4.0,4.0,RX4,NaN
2,2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.32 lbs,18.61,1.0,1.0,4.0,1.0,710,NaN
3,3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215 lbs,19.44,1.0,0.0,3.0,1.0,4,NaN
4,4,harnet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.44 lbs,17.02,NaN,0.0,3.0,2.0,Sportabout,NaN

Metadata

![mtcars_metadata.PNG]()

In [25]:
# We notice that there are two index columns
# Pandas automatically creates an index for every csv that you load
# Let's make things simpler by reloading the csv and telling pandas to use
# the column labelled 'index' as the index

cars = pd.read_csv('cars_features.csv', index_col='index')
cars.head()

,car,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,model.1,color
index,,,,,,,,,,,,,,,
0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.62 lbs,16.46,NaN,1.0,4.0,4.0,RX4,NaN
1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875 lbs,17.02,NaN,1.0,4.0,4.0,RX4,NaN
2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.32 lbs,18.61,1.0,1.0,4.0,1.0,710,NaN
3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215 lbs,19.44,1.0,0.0,3.0,1.0,4,NaN
4,harnet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.44 lbs,17.02,NaN,0.0,3.0,2.0,Sportabout,NaN

In [29]:
cars.info()
# cars.columns
# cars.describe()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63 entries, 0 to 62
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   car      51 non-null     object
 1   model    48 non-null     object
 2   mpg      51 non-null     float64
 3   cyl      51 non-null     float64
 4   disp     51 non-null     float64
 5   hp       51 non-null     float64
 6   drat     51 non-null     float64
 7   wt       53 non-null     object
 8   qsec     51 non-null     float64
 9   vs       24 non-null     float64
 10  am       51 non-null     float64
 11  gear     51 non-null     float64
 12  carb     51 non-null     float64
 13  model.1  48 non-null     object
 14  color    0 non-null      float64
dtypes: float64(11), object(4)
memory usage: 7.9+ KB

In [30]:
# We see that there are 63 rows and 15 columns.
# Let's double check:
print(len(cars),len(cars.columns))
cars.shape

63 15

(63, 15)

### Deal with the null values

In [31]:
# Which coloumn contain the most null values?

cars.isnull().sum().sort_values(ascending=False)

color      63
vs         39
model      15
model.1    15
car        12
mpg        12
cyl        12
disp       12
hp         12
drat       12
qsec       12
am         12
gear       12
carb       12
wt         10
dtype: int64

In [32]:
# Remove the color column

cars.drop('color',axis=1,inplace=True)
cars.head()

,car,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,model.1
index,,,,,,,,,,,,,,
0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.62 lbs,16.46,NaN,1.0,4.0,4.0,RX4
1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875 lbs,17.02,NaN,1.0,4.0,4.0,RX4
2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.32 lbs,18.61,1.0,1.0,4.0,1.0,710
3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215 lbs,19.44,1.0,0.0,3.0,1.0,4
4,harnet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.44 lbs,17.02,NaN,0.0,3.0,2.0,Sportabout

In [33]:
# Inspect the unique values in the vs column

cars.vs.unique()

array([nan,  1.])

In [34]:
# What value should the nulls be? Replace the nulls with the correct value

cars.vs=cars.vs.fillna(0)

In [35]:
# How many more nulls are there?
cars.isnull().sum().sort_values()

vs          0
wt         10
car        12
mpg        12
cyl        12
disp       12
hp         12
drat       12
qsec       12
am         12
gear       12
carb       12
model      15
model.1    15
dtype: int64

In [10]:
# Remove any columns which are unnecessary or are duplicates

cars=cars.drop(['model.1'],axis=1)

In [18]:
# Let's look at the end of the dataframe

cars.tail()

       car model  mpg  cyl  disp  hp  drat   wt  qsec   vs  am  gear  carb
index
58     NaN   NaN  NaN  NaN   NaN NaN   NaN  NaN   NaN  0.0 NaN   NaN   NaN
59     NaN   NaN  NaN  NaN   NaN NaN   NaN  NaN   NaN  0.0 NaN   NaN   NaN
60     NaN   NaN  NaN  NaN   NaN NaN   NaN  NaN   NaN  0.0 NaN   NaN   NaN
61     NaN   NaN  NaN  NaN   NaN NaN   NaN  NaN   NaN  0.0 NaN   NaN   NaN
62     NaN   NaN  NaN  NaN   NaN NaN   NaN  NaN   NaN  0.0 NaN   NaN   NaN

In [39]:
# Delete any rows that still contain null values. Why must this step be performed last?

cars = cars.dropna(how='any')
cars.shape

(48, 15)

In [ ]:
cars.isnull().sum()

car      0
model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [ ]:
# let us reset the index because there will be missing index values after we drop rows
cars = cars.reset_index(drop=True)

### Clean up the columns

In [19]:
cars.head()

,car,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
index,,,,,,,,,,,,,
0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.62 lbs,16.46,0.0,1.0,4.0,4.0
1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875 lbs,17.02,0.0,1.0,4.0,4.0
2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.32 lbs,18.61,1.0,1.0,4.0,1.0
3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215 lbs,19.44,1.0,0.0,3.0,1.0
4,harnet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.44 lbs,17.02,0.0,0.0,3.0,2.0

In [ ]:
# Rename the car column to something more appropriate

cars.rename(columns={'car':'make'},inplace=True)

In [ ]:
cars.head()

,make,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.62 lbs,16.46,0.0,1.0,4.0,4.0
1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875 lbs,17.02,0.0,1.0,4.0,4.0
2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.32 lbs,18.61,1.0,1.0,4.0,1.0
3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215 lbs,19.44,1.0,0.0,3.0,1.0
4,harnet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.44 lbs,17.02,0.0,0.0,3.0,2.0

### Final cleaning steps

In [ ]:
# Correct any spelling errors you find in the dataset

# cars.model.unique()
cars.model.value_counts().sort_index()

128            1
142E           1
230            2
240D           3
280            1
280C           3
360            1
4              1
450SE          1
450SL          3
450SLC         1
710            1
914-2          1
Bora           1
Challenger     1
Civic          1
Continental    2
Corolla        1
Corona         3
Dino           1
Europa         2
Firebird       3
Fleetwood      1
Imperial       1
Javelin        1
Pantera        1
RX4            3
Sportabout     3
X1-9           1
Z28            2
Name: model, dtype: int64

In [ ]:
cars.make.unique()
# cars.make.value_counts().sort_index()

array(['Mazda', 'Datsun', 'Hornet', 'harnet', 'Duster', 'Merc', 'nerc',
       'merc', 'Cadillac', 'Lincoln', 'Chrysler', 'Fiat', 'Honda',
       'toyota', 'Toyota', 'Dodge', 'AMC', 'Camaro', 'Pontiac', 'Porsche',
       'Lotus', 'Ford', 'Ferrari', 'Maserati', 'Volvo'], dtype=object)

In [ ]:
# We can see in the make column there are duplicates because of spelling mistakes and case errors
sorted(cars.make.unique(), key=str.casefold)  # casefold is used to ignore case

['AMC',
 'Cadillac',
 'Camaro',
 'Chrysler',
 'Datsun',
 'Dodge',
 'Duster',
 'Ferrari',
 'Fiat',
 'Ford',
 'harnet',
 'Honda',
 'Hornet',
 'Lincoln',
 'Lotus',
 'Maserati',
 'Mazda',
 'Merc',
 'merc',
 'nerc',
 'Pontiac',
 'Porsche',
 'toyota',
 'Toyota',
 'Volvo']

In [ ]:
# We can find the spelling errors by inspection

cars = cars.replace(
    {'harnet'   : 'Hornet',
    'merc'      : 'Merc',
    'nerc'      : 'Merc',
    'toyota'    : 'Toyota'})

In [ ]:
cars.make.unique()

array(['Mazda', 'Datsun', 'Hornet', 'Duster', 'Merc', 'Cadillac',
       'Lincoln', 'Chrysler', 'Fiat', 'Honda', 'Toyota', 'Dodge', 'AMC',
       'Camaro', 'Pontiac', 'Porsche', 'Lotus', 'Ford', 'Ferrari',
       'Maserati', 'Volvo'], dtype=object)

In [ ]:
# Inspect the weight in pounds column, why can't you try to find the mean of this column?

cars.wt.mean()

TypeError: ignored

In [ ]:
cars['wt'].dtype # Python stores strings as 'object' datatype

dtype('O')

In [ ]:
# Remove the 'lbs' from each value in the weight column

cars.wt=cars.wt.str.replace(' lbs','')

In [ ]:
# Change the datatype of the weight in pounds column to a float

cars.wt=cars.wt.astype('float')

# We will also rename the weight column so it shows what unit of measurement is being used.
# It is always a good idea to make your column names be as descriptive as possible.
cars = cars.rename(columns={"wt": "weight_lbs"})

In [ ]:
cars.weight_lbs.mean()

3.2607083333333335

In [ ]:
# How many duplicate rows exist within this dataset?

cars.duplicated().sum()

17

In [ ]:
# Remove any duplicated rows. Why should you do this step after correcting spelling mistakes?

cars=cars.drop_duplicates()

In [ ]:
cars.shape

(31, 14)

In [ ]:
# Save the data as a CSV, calling the file a new name, different to the original

cars.to_csv('cars_features_clean.csv',index=False)

In [48]:
# It is good when you are learning to do all the above step by step
# However, over time, you will be able to do all this in a few lines of code
cars_df = pd.read_csv('cars_features.csv', index_col='index')

# Drop irrelevant columns
cars_df = cars_df.drop(['color', 'model.1'], axis=1)

# Data cleaning
cars_df = (
    cars_df
    .dropna(how='all')
    .assign(vs=cars_df['vs'].fillna(0))
    .dropna(how='any')
    .assign(wt=cars_df['wt'].str.replace(' lbs', ''))
    .rename(columns={"wt": "weight_lbs", "car": "make"})
    .assign(weight_lbs = lambda x: x['weight_lbs'].astype(float))
    .replace({'harnet':'Hornet', 'merc':'Merc', 'nerc':'Merc', 'toyota':'Toyota'})
    .drop_duplicates()
    .reset_index(drop=True)
)

### Stretch

A couple of useful functions for parsing a dataframe are the map and apply functions. <br><br> `map` will loop through a column and replace any values as defined by a dictionary. <br><br> `apply` will loop through a column and apply a function to each value.

In [ ]:
cars=pd.read_csv('/content/cars_features_clean.csv')

In [ ]:
cars.head()

,make,model,mpg,cyl,disp,hp,drat,weight_lbs,qsec,vs,am,gear,carb
0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0.0,1.0,4.0,4.0
1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0
2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0
4,Hornet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0

In [ ]:
# For example, with map we can label cars with am 0 as automatic and 1 as manual

cars.am.map({0:'automatic',1:'manual'})

0        manual
1        manual
2        manual
3     automatic
4     automatic
5     automatic
6     automatic
7     automatic
8     automatic
9     automatic
10    automatic
11    automatic
12    automatic
13    automatic
14    automatic
15    automatic
16       manual
17       manual
18       manual
19    automatic
20    automatic
21    automatic
22    automatic
23    automatic
24       manual
25       manual
26       manual
27       manual
28       manual
29       manual
30       manual
Name: am, dtype: object

In [ ]:
# We can then assign this series as a new column:

cars['transmission']=cars.am.map({0:'automatic',1:'manual'})
cars.head()

,make,model,mpg,cyl,disp,hp,drat,weight_lbs,qsec,vs,am,gear,carb,transmission
0,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0.0,1.0,4.0,4.0,manual
1,Mazda,RX4,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0,manual
2,Datsun,710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0,manual
3,Hornet,4,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0,automatic
4,Hornet,Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0,automatic

To make the most use out of `apply` we need to introduce `lambda functions`. These are small functions that take any number of arguments but return one result

In [ ]:
lam_func= lambda x: x*5

print(lam_func(3))

15

Lambda functions can also include if statements, although you must always provide an else

In [ ]:
lam_func= lambda x: 'Yes' if x>10 else 'No'

print(lam_func(12))

Yes

We can combine these types of functions with `.apply` to get some powerful results:

In [ ]:
cars.am.apply(lambda x: 'Automatic' if x==0 else 'Manual')

0        Manual
1        Manual
2        Manual
3     Automatic
4     Automatic
5     Automatic
6     Automatic
7     Automatic
8     Automatic
9     Automatic
10    Automatic
11    Automatic
12    Automatic
13    Automatic
14    Automatic
15    Automatic
16       Manual
17       Manual
18       Manual
19    Automatic
20    Automatic
21    Automatic
22    Automatic
23    Automatic
24       Manual
25       Manual
26       Manual
27       Manual
28       Manual
29       Manual
30       Manual
Name: am, dtype: object

We can even use `apply` with external functions:

In [ ]:
def multiply_five(x):
    return 5*x

cars.cyl.apply(lambda x: multiply_five(x))

0     30.0
1     30.0
2     20.0
3     30.0
4     40.0
5     40.0
6     20.0
7     20.0
8     30.0
9     30.0
10    40.0
11    40.0
12    40.0
13    40.0
14    40.0
15    40.0
16    20.0
17    20.0
18    20.0
19    20.0
20    40.0
21    40.0
22    40.0
23    40.0
24    20.0
25    20.0
26    20.0
27    40.0
28    30.0
29    40.0
30    20.0
Name: cyl, dtype: float64

The `apply` function in pandas can be used in data cleaning (e.g. changing data types, adding or removing characters, etc) or creating new columns based on existing values.

## Practice

In [42]:
# 1: Use .map to create a new column which labels a car as v-shaped engine or straight engine

In [43]:
# 2: use .apply to add 'seconds' to each value in the qsec column
# This is not something you would normally do; it is simply to show you how to use .apply

In [44]:
# 3: Use .apply to convent the gear column into an integer datatype

In [ ]:
# 4: Create a new column which returns the length of the cars make and manufacturer